version: '3.1'

services:
  backend:
    image: loeservice-php8.2
    environment:
      ALLOW_OVERRIDE: true
      MYSQL_HOST: $DOCKER_MYSQL_HOST
      MYSQL_USER: $DOCKER_MYSQL_USER
      MYSQL_PASSWORD: $DOCKER_MYSQL_PASS
      OAUTH_JWKS_URI: $DOCKER_OAUTH_JWKS_URI
      OAUTH_CACHE_PATH: $DOCKER_OAUTH_CACHE_PATH
      OATH_CACHE_TTL: $DOCKER_OATH_CACHE_TTL
      OATH_AUDIENCE: $DOCKER_OATH_AUDIENCE
      IMDB_API_KEY: $IMDB_API_KEY
      COMICVINE_API_KEY: $COMICVINE_API_KEY
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '9669:80'
    volumes:
      #use these to redirect access logs away from stdout
      - ./apache-logs.conf:/etc/apache2/conf-enabled/custom-logs.conf
      - /tmp/loe-api-logs/:/var/log/apache2
